#!/usr/bin/env node
/**
 * Simple Figma design token fetcher.
 * Usage: FIGMA_TOKEN=xxx FIGMA_FILE_ID=yyy node scripts/figma/fetch-tokens.mjs
 * Outputs CSS variables to frontend/styles/tokens.css and a TS map to frontend/utils/designTokens.ts
 */
import fs from 'fs';
import path from 'path';
import https from 'https';

const FIGMA_TOKEN = process.env.FIGMA_TOKEN;
const FILE_ID = process.env.FIGMA_FILE_ID;
if (!FIGMA_TOKEN || !FILE_ID) {
  console.error('Missing FIGMA_TOKEN or FIGMA_FILE_ID env variables');
  process.exit(1);
}

function figmaGet(endpoint) {
  return new Promise((resolve, reject) => {
    const opts = {
      hostname: 'api.figma.com',
      path: `/v1${endpoint}`,
      headers: { 'X-Figma-Token': FIGMA_TOKEN }
    };
    https
      .get(opts, res => {
        let data = '';
        res.on('data', chunk => (data += chunk));
        res.on('end', () => {
          try { resolve(JSON.parse(data)); } catch (e) { reject(e); }
        });
      })
      .on('error', reject);
  });
}

(async () => {
  console.log('Fetching Figma file...');
  const file = await figmaGet(`/files/${FILE_ID}`);
  // Naive example: extract color styles
  const styles = file.styles || {};
  const nodesIndex = {};
  function indexNode(node) {
    nodesIndex[node.id] = node;
    if (node.children) node.children.forEach(indexNode);
  }
  indexNode(file.document);

  const colorVars = [];
  for (const styleId in styles) {
    const style = styles[styleId];
    if (style.styleType === 'FILL') {
      const node = nodesIndex[style.nodeId];
      const fills = node?.fills || [];
      const solid = fills.find(f => f.type === 'SOLID');
      if (solid) {
        const { r, g, b } = solid.color;
        const name = style.name.replace(/\s+/g, '-').toLowerCase();
        const hex = '#' + [r, g, b].map(v => Math.round(v * 255).toString(16).padStart(2, '0')).join('');
        colorVars.push({ name, hex });
      }
    }
  }

  // Merge with brand defaults
  const brandDefaults = [
    { name: 'brand-terracotta', hex: '#F07B52' },
    { name: 'brand-teal', hex: '#2BB6A3' },
    { name: 'brand-pastel-yellow', hex: '#F9E5A1' },
    { name: 'brand-charcoal', hex: '#333333' },
    { name: 'brand-white', hex: '#FFFFFF' }
  ];

  const merged = new Map();
  [...brandDefaults, ...colorVars].forEach(c => merged.set(c.name, c.hex));

  const css = `/* AUTO-GENERATED: Design Tokens from Figma + Brand Defaults */\n:root{\n${[...merged.entries()].map(([n,v]) => `  --color-${n}: ${v};`).join('\n')}\n}`;
  const ts = `// AUTO-GENERATED by fetch-tokens.mjs\nexport const designTokens = {\n${[...merged.entries()].map(([n,v]) => `  '${n}': '${v}',`).join('\n')}\n} as const;\n`;

  const tokensCssPath = path.resolve('frontend/styles/tokens.css');
  const tokensTsPath = path.resolve('frontend/utils/designTokens.ts');
  fs.writeFileSync(tokensCssPath, css);
  fs.writeFileSync(tokensTsPath, ts);
  console.log('Tokens written to', tokensCssPath, 'and', tokensTsPath);
})();
