from fastapi import HTTPException
import razorpay

# Initialize Razorpay client
razorpay_client = razorpay.Client(auth=("YOUR_RAZORPAY_KEY_ID", "YOUR_RAZORPAY_SECRET"))

def create_order(amount: float, currency: str, receipt: str):
    """
    Create a new order in Razorpay.
    
    Args:
        amount (float): The amount for the order.
        currency (str): The currency for the order.
        receipt (str): The receipt identifier for the order.
    
    Returns:
        dict: The response from Razorpay containing order details.
    """
    try:
        order_data = {
            "amount": amount * 100,  # Amount in paise
            "currency": currency,
            "receipt": receipt,
            "payment_capture": 1  # Auto capture
        }
        order = razorpay_client.order.create(data=order_data)
        return order
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

def verify_payment(payment_id: str, order_id: str, signature: str):
    """
    Verify the payment signature from Razorpay.
    
    Args:
        payment_id (str): The payment ID from Razorpay.
        order_id (str): The order ID from Razorpay.
        signature (str): The signature generated by Razorpay.
    
    Returns:
        bool: True if the signature is valid, False otherwise.
    """
    generated_signature = f"{order_id}|{payment_id}"
    import hashlib
    import hmac

    expected_signature = hmac.new(
        key=b"YOUR_RAZORPAY_SECRET",
        msg=generated_signature.encode('utf-8'),
        digestmod=hashlib.sha256
    ).hexdigest()

    return expected_signature == signature

# TODO: Implement additional functions for refunds, capturing payments, etc.